import heapq
import random
import csv
import os
from collections import defaultdict

class AdvancedP2PSimulator:
    """
    Advanced Discrete-Event Simulator (DES) for P2P Secure File Exchange on Private Blockchain.
    Models not just consensus time, but also Cryptographic CPU load, Network Bandwidth, and Full Propagation.
    """
    def __init__(self, num_nodes, file_size_mb=5):
        self.num_nodes = num_nodes
        self.file_size_mb = file_size_mb
        
        # Hardware & Network Constants
        self.pow_mean_ms = 100
        self.net_latency_mean_ms = 40
        self.packet_loss_prob = 0.02
        self.aes_encrypt_speed_mb_per_s = 250.0  # 250 MB/s AES encryption
        self.rsa_encrypt_ms = 2.0                # 2ms per RSA encryption (for AES key wrapper)
        self.network_bandwidth_mbps = 1000.0     # Gigabit ethernet (125 MB/s)
        
        self.time = 0.0
        self.events = [] 
        
        # Tracking metrics
        self.block_votes = defaultdict(set)
        self.block_start_times = {}
        self.metrics = {
            'consensus_50_ms': {},   # Time to 50% + 1
            'propagation_100_ms': {},# Time to 100% nodes
            'crypto_cpu_ms': {},     # Time spent on encryption
            'total_bandwidth_mb': {} # Total network load generated by sender
        }

    def schedule(self, delay, event_type, *args):
        heapq.heappush(self.events, (self.time + delay, event_type, args))

    def run(self, num_blocks=5):
        for i in range(num_blocks):
            start_time = random.uniform(0, 200)
            node_id = random.randint(0, self.num_nodes - 1)
            block_id = f"block_{i}"
            
            self.block_start_times[block_id] = start_time
            self.schedule(start_time, 'INIT_FILE_TRANSFER', node_id, block_id)

        while self.events:
            self.time, event_type, args = heapq.heappop(self.events)
            
            if event_type == 'INIT_FILE_TRANSFER':
                node_id, block_id = args
                
                # 1. AES Encryption Time (O(Size)) with CPU scheduling jitter
                t_aes_base = (self.file_size_mb / self.aes_encrypt_speed_mb_per_s) * 1000
                t_aes = max(1, random.gauss(t_aes_base, t_aes_base * 0.05))
                # 2. RSA Encryption of AES key for EACH peer (O(N)) with jitter
                t_rsa_per_key = max(0.5, random.gauss(self.rsa_encrypt_ms, self.rsa_encrypt_ms * 0.05))
                t_rsa = self.num_nodes * t_rsa_per_key
                
                total_crypto_time = t_aes + t_rsa
                self.metrics['crypto_cpu_ms'][block_id] = total_crypto_time
                self.metrics['total_bandwidth_mb'][block_id] = self.num_nodes * self.file_size_mb
                
                self.schedule(total_crypto_time, 'START_POW', node_id, block_id)
                
            elif event_type == 'START_POW':
                node_id, block_id = args
                t_pow = max(10, random.gauss(self.pow_mean_ms, self.pow_mean_ms * 0.2))
                self.schedule(t_pow, 'BROADCAST', node_id, block_id)
                
            elif event_type == 'BROADCAST':
                node_id, block_id = args
                
                # Model network serialization and transmission delay based on bandwidth
                # Sending N copies of the file sequentially through a 1 Gbps NIC
                transfer_delay = (self.file_size_mb / (self.network_bandwidth_mbps / 8)) * 1000
                
                for i, peer_id in enumerate(range(self.num_nodes)):
                    if peer_id == node_id: continue
                    if random.random() < self.packet_loss_prob: continue 
                    
                    latency = max(5, random.gauss(self.net_latency_mean_ms, self.net_latency_mean_ms * 0.3))
                    t_val = max(1, random.gauss(5, 1))
                    
                    # Each peer receives the file slightly later due to sender's sequential upload bottleneck
                    queue_delay = i * transfer_delay
                    
                    self.schedule(latency + t_val + queue_delay, 'RECEIVE_VALIDATE', peer_id, node_id, block_id)
                    
            elif event_type == 'RECEIVE_VALIDATE':
                peer_id, sender_id, block_id = args
                self.block_votes[block_id].add(peer_id)
                
                current_votes = len(self.block_votes[block_id])
                majority = (self.num_nodes // 2) + 1
                
                if current_votes == majority and block_id not in self.metrics['consensus_50_ms']:
                    self.metrics['consensus_50_ms'][block_id] = self.time - self.block_start_times[block_id]
                    
                # Full propagation (accounting for 2% packet loss, so we check for 98% nodes)
                threshold_100 = int(self.num_nodes * 0.98) - 1
                if current_votes >= threshold_100 and block_id not in self.metrics['propagation_100_ms']:
                    self.metrics['propagation_100_ms'][block_id] = self.time - self.block_start_times[block_id]

        # Calculate averages for this run
        def get_avg(metric_dict):
            if not metric_dict: return 0
            return sum(metric_dict.values()) / len(metric_dict)
            
        # Calculate TPS (Files processed per second)
        # Time from first block start to last block consensus
        if self.metrics['consensus_50_ms']:
            max_time = max(self.metrics['consensus_50_ms'].values())
            tps = num_blocks / (max_time / 1000.0) if max_time > 0 else 0
        else:
            tps = 0
            
        global_storage_gb = (self.num_nodes * self.file_size_mb) / 1024.0
            
        return {
            'consensus_ms': get_avg(self.metrics['consensus_50_ms']),
            'propagation_ms': get_avg(self.metrics['propagation_100_ms']),
            'crypto_ms': get_avg(self.metrics['crypto_cpu_ms']),
            'bandwidth_mb': get_avg(self.metrics['total_bandwidth_mb']),
            'tps': tps,
            'storage_gb': global_storage_gb
        }

def run_scalability_experiment():
    print("="*100)
    print(" ADVANCED SCALABILITY SIMULATION (Cryptography, Network, Consensus & Throughput)")
    print("="*100)
    # Кількість нод для тестування (від малого кластера до глобальної мережі)
    node_counts = [5, 10, 50, 100, 250, 500, 1000, 5000, 10000, 25000, 50000, 100000]
    results = []
    
    header = f"{'Nodes (N)':<10} | {'Crypto (ms)':<12} | {'Consensus(ms)':<14} | {'Propagate(ms)':<14} | {'Bandwidth(MB)':<14} | {'Storage(GB)':<12} | {'Max TPS':<10}"
    print(header)
    print("-" * 100)
    
    for n in node_counts:
        simulations_runs = 3
        totals = {'consensus_ms': 0, 'propagation_ms': 0, 'crypto_ms': 0, 'bandwidth_mb': 0, 'tps': 0, 'storage_gb': 0}
        
        for _ in range(simulations_runs):
            sim = AdvancedP2PSimulator(num_nodes=n, file_size_mb=5.0) # 5MB dummy file
            res = sim.run(num_blocks=3)
            for k in totals:
                totals[k] += res[k]
                
        avg_res = {k: v/simulations_runs for k, v in totals.items()}
        results.append([n, avg_res['crypto_ms'], avg_res['consensus_ms'], avg_res['propagation_ms'], avg_res['bandwidth_mb'], avg_res['storage_gb'], avg_res['tps']])
        
        print(f"{n:<10} | {avg_res['crypto_ms']:<12.2f} | {avg_res['consensus_ms']:<14.2f} | {avg_res['propagation_ms']:<14.2f} | {avg_res['bandwidth_mb']:<14.2f} | {avg_res['storage_gb']:<12.2f} | {avg_res['tps']:<10.4f}")

    results_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "results")
    if not os.path.exists(results_dir):
        os.makedirs(results_dir)
        
    csv_path = os.path.join(results_dir, "advanced_scalability.csv")
    with open(csv_path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Nodes_N', 'Crypto_CPU_ms', 'Consensus_Majority_ms', 'Full_Propagation_ms', 'Sender_Bandwidth_MB', 'Global_Storage_GB', 'Throughput_TPS'])
        for row in results:
            writer.writerow([round(x, 4) if isinstance(x, float) else x for x in row])
            
    print("-" * 100)
    print(f"[!] Результати збережено у: {csv_path}")

if __name__ == "__main__":
    run_scalability_experiment()
